name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies for System.Drawing
        run: sudo apt-get install -y libgdiplus

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: List output files
        run: ls -R ./meryem.hamidialaoui.ObjectDetection.Tests/bin/Debug/net8.0

      - name: Check libgdiplus
        run: dpkg -l | grep libgdiplus

      - name: Run Tests
        run: dotnet test meryem.hamidialaoui.ObjectDetection.sln --no-build --verbosity normal --blame

  publish:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies for System.Drawing
        run: sudo apt-get install -y libgdiplus

      - name: Publish Console App
        run: dotnet publish meryem.hamidialaoui.ObjectDetection.Console --configuration Release --output ./publish --self-contained --runtime win10-x64

      - name: Upload Published Files
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: ./publish
