name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies for System.Drawing
        run: sudo apt-get install -y libgdiplus

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal

  
      

  publish:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer le SDK .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # Étape 3 : Publier le projet console en mode autonome
      - name: Publish console app
        run: dotnet publish meryem.hamidialaoui.ObjectDetection.Console --configuration Release --output ./publish --self-contained --runtime win10-x64
